-- Create Snowflake State
CREATE STAGE netflixstage
  URL='s3://netflixdataset-chayuth'
  CREDENTIALS=(AWS_KEY_ID='AKIAZN7GCHFHFSBTRXTJ' AWS_SECRET_KEY='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');

-- Set defaults
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MOVIELENS;
USE SCHEMA RAW;